### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by slang25** [dustinmoris/Giraffe#15]
`AspNetCore.Lambda` would be a great name, however there is a lot of buzz at the moment about AWS Lambda, and it's recent .NET Core support (and even F# support!). I wonder if this confusion is limited to me and the people I surround myself with as I am working in a company using AWS heavily, or if this is a wider problem.

Here's a quick list just to illustrate what people might get in a google search:
- [F# on  AWS Lambda](http://lukemerrett.com/fsharp-on-aws-lambda/)
- [AWS Lambda for .NET Core](https://github.com/aws/aws-lambda-dotnet/)
- [Amazon.Lambda.AspNetCoreServer](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer) Amazons library for making AspNetCore apps work on Lambda, the naming here is very close.

I wonder what your feeling is on the name, and given that this is in alpha, is this already set in stone for you?

Of course, I could be totally wrong about this.

Also you had a shout out on the [ASP.NET Community Standup](https://www.youtube.com/watch?v=q88i3oDWp80) @ 23:30, I think Damian Edwards is right and an ASP.NET Core template needs to come from the community and I would love to see this library be be part of that template, getting the name right would go a long way towards that IMO.

**Comment by dustinmoris** [comment]
Man that is funny that you created this issue now, because I was literally JUST about to create such an issue myself and include a poll for people to help me decide.

I think the confusion with AWS Lambda is real and I had two ideas myself:

- Giraffe
- Brachios

Both names sound weird initially, but I was looking for a good Lambda logo and when I saw this:

![Lambda Logo from Wikimedia](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Orange_lambda.svg/2000px-Orange_lambda.svg.png)

I thought it looks a little bit like these:

![Giraffe](https://s-media-cache-ak0.pinimg.com/236x/26/62/e8/2662e81c190346aac535c71b38259571.jpg)
![Brachiossaurus](https://image.freepik.com/free-icon/dinosaur-shape-of-brachiosaurus_318-62927.jpg)

Obviously both names are very playful and don't mean a lot, but which web product name actually means anything today hey?

It would be memorable and I could easily design a Lambda looking giraffe or brachiossaurus to go along with it as the logo.

**Comment by dustinmoris** [comment]
Also I was thinking about the template thing as well. The name ASP.NET Core Lambda would make it a bit more cumbersome for a `dotnet new -type aspnetcorelambda` CLI command. Something like `dotnet new -type giraffe` would perhaps be easier

**Comment by dbettin** [comment]
Agree about the name confusion.  In fact, during the asp.net core standup directly after they mentioned this project they mentioned an AWS lambda core project!

I really like the name Eiffel.  He was a great builder and architect. Additionally, the Eiffel Tower resembles the Lambda logo.

**Comment by dustinmoris** [comment]
Eiffel is a good name indeed.

**Comment by slang25** [comment]
I'm liking Giraffe right now 😃 They are all good suggestions though.

**Comment by stevedesmond-ca** [comment]
What's the important part / differentiator? That's it's more functional, or that it's F#? Maybe that could lead in the right direction.

**Comment by ErikSchierboom** [comment]
I like Giraffe :)

**Comment by dustinmoris** [comment]
@stevedesmond-ca Hmm.. I don't know, I feel like in .NET they are both kind of the same. Even though you can mimic functional programming in C# it is nowhere near as nice or intuitive as in F#, not even with C# 7. I think when people want to go functional in .NET it basically means adopting F#. What did you have in mind with both options?

**Comment by yawaramin** [comment]
How about Arrow.Net? 'Arrow' as in the function arrow `->`, 'Arrow.Net' to be reminiscent of 'ASP.Net'.

**Comment by stevedesmond-ca** [comment]
Maybe it's just me, but a pet peeve of mine in when projects are called
Something.NET but they don't own that internet domain.

I do like the Arrow part though... Arrow Core?

On Feb 16, 2017 11:37 PM, "Yawar Amin" <notifications@github.com> wrote:

How about Arrow.Net? 'Arrow' as in the function arrow ->, 'Arrow.Net' to be
reminiscent of 'ASP.Net'.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dustinmoris/AspNetCore.Lambda/issues/15#issuecomment-280549887>,
or mute the thread

**Comment by dustinmoris** [comment]
Thanks for all the feedback so far.

**Giraffe**:
So far I count myself + 2 other people who like the name.

**Eiffel**:
I really like this one as well and if I had to decide myself then I'd struggle, because I see it on parity with Giraffe. If I count myself in then it's 2 votes in total for Eiffel.

**Arrow.Net / Arrow Core**:
Personally I am not a big fan of {something}.Net names and I am also not very keen on overloading "Core" even more as it already is. I know this sounds contradicting given that I named the library "ASP.NET Core Lambda", but the only reason I chose this name was to express that it is a functional framework (Lambda) for ASP.NET Core.

As we all agree it's not a great name (otherwise this issue wouldn't exist :)) and I'd rather move away from similar troubling names like {something}.net or {something} Core, etc.

If I rename the project then it needs to be a name that is very clear, search and spell friendly and unique (as far as concerned in the .NET space) so that I don't have to go through that exercise a second time in the future.

I'll leave this issue open for few more days and see if there's more ideas/suggestions coming in and then I'll make a call :)

**Comment by yawaramin** [comment]
Hmm ... Arrowasp?

**Comment by ErikSchierboom** [comment]
As for naming, `Eiffel` is of course also a programming language, although a very popular one. So that might lead to some search issues.

**Comment by dbettin** [comment]
I would say the name Giraffe would lead to more search conflicts than Eiffel. 

 Also, I have assumed it would still be called something akin to "Eiffel for Asp.net Core".  So both points might be futile.

**Comment by slang25** [comment]
@dbettin How so? Here are 2 search results:
https://www.google.co.uk/search?q=Giraffe+.net&oq=Giraffe+.net&aqs=chrome..69i57.1947j0j1&sourceid=chrome&ie=UTF-8
https://www.google.co.uk/search?q=Eiffel+.net&oq=Eiffel+.net&aqs=chrome..69i57.7496j0j1&sourceid=chrome&ie=UTF-8

The Eiffel results are actually .NET related, I think in practice either of those names won't lead to any confusion, but I cannot see how Giraffe would lead to more search conflicts that Eiffel.

**Comment by dbettin** [comment]
I was referring to generic queries. But like you said,  both are fine in practice.  I believe most people would search for Eiffel F# or Giraffe F#.

**Comment by jackfoxy** [comment]
A meaningful name can help marketing. I like something with lambda in it. That forms an image of functional programming. ASP is associated with the Microsoft stack. How many people still know it stood for Active Server Page? The original tech and today's ASP.NET are pretty removed. How about LambdaASP? Shorter, and shouldn't be confused with AWS Lambda.

**Comment by nicolocodev** [comment]
yup, i think the "asp" must be in the name 'cause this runs on top of it. I like something like @jackfoxy proposed, or even shorter, lamd*A*sp, reusing that *a*. And the logo would be replacing that *A* whit the lambda symbol. What do you think?

**Comment by slang25** [comment]
@nicolocodev `lambdΛsp`
I think that lambda is a confusing term (see first post), if it wasn't then `AspNetCore.Lambda` is descriptive and is not a problem.

**Comment by dustinmoris** [comment]
Hey everyone, thanks for the feedback. I would have to recount again, but by briefly looking at the responses and upvotes I believe Giraffe is still ahead and I was already playing with some logo ideas for that name as well.

Here are my current thoughts:

I agree that a link to ASP.NET Core would be nice, because this framework is essentially designed for it. I also agree though that there should be an "ASP" free name, which can be easily used in everyday lingo, search results, etc.

Let's say we go with the name Giraffe. I think the long official name could be still "ASP.NET Core Giraffe" or "ASP.NET Giraffe", but short and more commonly used it would be simply "Giraffe". I think the logo could look very much like a giraffe looking lambda sign and I was also playing with the idea that the text could be written a bit like "Gira#e" where the # can be two "f" sightly designed into a # sign. or maybe one f and the other f an # or so... I don't know.. I am not really the creative guy, but I will ask some of my work mates who do branding for a living to help me with that :)

My plan is to finalize the Razor work started by @nicolocodev this weekend before doing any renaming (because that will create even more merging issues) and after that I will come back to this thread and do a final check.

**Comment by mikeball** [comment]
Just to throw a couple other ideas out there that try to associate with the letter F.

phaser mvc (sounds like F)

asp.net [animal-that-starts-with-letter-f] mvc
e.g. falcon, ferret, finch, frog, flamingo, fox

asp.net f'n mvc (as in we use "asp.net fn mvc" my personal favorite would be so great to say in business meetings)

or maybe play off the language improvement from F#?
sharper mvc

or along the lines of arrows
quiver mvc
fletch mvc (the feathers on arrows)

**Comment by slang25** [comment]
@mikeball I would try to avoid MVC as this is what this library kills and replaces. Sounds like @dustinmoris has landed on a name now.

**Comment by nojaf** [comment]
I'm in favor for Giraffe, it's simple and has a nice ring to it. 
I don't really think that the name should contain any references to a functional programming thing, ASP, .NET or Core.

**Comment by dustinmoris** [comment]
I renamed the project to Giraffe now. Thank you all for your input!

**Comment by dustinmoris** [comment]
Hi all, I'd like to request your help again for finding the right logo now. Please see #43. Thank you!
