### ISSUE TITLE
Please remove operators like fish and => 

### ISSUE THREAD

**Issue by forki** [dustinmoris/Giraffe#159]
we don't need them. Newcomers will appreciate the usage of `( ... )`

**Comment by forki** [comment]
better remove them now then later when things will break

(we can still add them if REALLY needed)

**Comment by forki** [comment]
ok keep the fish, but try to do all docs without it. Whenever you need it, think about a named version of the same operation.
You will be amazed ;-)

**Comment by dustinmoris** [comment]
@forki From the fsharp chat I can understand why you would like to remove the `<|` operator from the docs, but I thought the `>=>` made things a lot easier. Counting myself still as an F# beginner I remember very well when I looked at Suave for the first time and saw the fish operator. Even though I didn't know what it exactly meant, by the look of the code and how apps were composed through `>=>` I could very easily read and understand what was happening, so I thought it was really good to have.

It's also worth noting that we need to find the right balance between making Giraffe easy for F# beginners, but also make it intuitive for F# power users, since being a beginner is only temporarily and things like the fish operator can very quickly be learnt by reading some Scott Wlaschin articles.

**Comment by gerardtoconnor** [comment]
cool, we can remove `=>` & `<|` from docs, leave fish

on side note, there is function `compose` that will do same as operator but not as clean writing code and will become nightmare when nesting long complex paths
```
let app = compose (setStatusCode 404) (text "not found")
```

**Comment by forki** [comment]
Leave fish. But regarding that very last sample. That's Successful.Ok -
without the fish. Reads million times better

Am 30.11.2017 18:28 schrieb "Gerard" <notifications@github.com>:

**Comment by forki** [comment]
Ah sorry it's NOT_FOUND.

calling it a day...

Am 30.11.2017 18:38 schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

Leave fish. But regarding that very last sample. That's Successful.Ok -
without the fish. Reads million times better

Am 30.11.2017 18:28 schrieb "Gerard" <notifications@github.com>:

**Comment by dustinmoris** [comment]
Removed it from the docs as requested. Thanks for helping to make the docs better!
