### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Neftedollar** [dustinmoris/Giraffe#33]
Hi! 
Will you provide roadmap?

**Comment by dustinmoris** [comment]
Hi, I don't really have a roadmap at the moment. There is not a lot of bugs/feature requests coming in where I feel I need to formally put a roadmap together. At the moment I use Giraffe in a few projects of my own and when I run into my own shortcomings then I slowly integrate those things into the official package.

I have tagged it with alpha because I don't really know how many people actually use it beyond myself and I am not sure if the library has been sufficiently tested or if there might be some bigger API changes requested any time soon. As far as I know it is fairly stable, but every so often I still introduce minor breaking changes to iron it out some corners of the library (check the latest release notes).

The alpha tag might be a little bit misrepresenting, because the library is fairly stable, but on the other hand I don't feel in a rush to prematurely label it beta or RTM if I know that I am still tweaking it here and there.

Saying that, I am open to discuss any ideas you have? What would you like to happen?

**Comment by dustinmoris** [comment]
If you are interested I am currently working on a [negotiate handler](https://github.com/dustinmoris/Giraffe/blob/feature/negotiate_handler/src/Giraffe/HttpHandlers.fs#L402). A first example can be seen in [the tests](https://github.com/dustinmoris/Giraffe/blob/feature/negotiate_handler/tests/Giraffe.Tests/HttpHandlerTests.fs#L795) and I expect to have a first working version ready this weekend.

**Comment by dustinmoris** [comment]
Hi, I created a beta milestone and updated all remaining issues: https://github.com/dustinmoris/Giraffe/milestones

Once I closed all these issues and nothing else came up then I will transition the project to beta. Hopefully the time between beta and RC will be a lot quicker, but it really depends what other suggestions/issues will come in after that.

There's still some quite fundamental changes being discussed and worked on like #53 for example.

Hope that answers you question!
