### ISSUE TITLE
Websockets suaveio way?

### ISSUE THREAD

**Issue by Neftedollar** [dustinmoris/Giraffe#36]
Hi! 
Giraffe expose very useful suaveio-like api for .net  core? will you go further and provide same socket api?

**Comment by dustinmoris** [comment]
Hi, ASP.NET Core already comes with a web socket server implementation that can be used from F#. You can find a [C# example here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets#how-to-use-it), but it would be the same in F#. The boilerplate to set up the socket server is very minimal in its current form and once you have established a connection the communication could be literally anything so I don't know if there is additional layer that Giraffe could expose to help with web sockets any more than what you already can do with ASP.NET Core. Did you have something specific in mind?

**Comment by Neftedollar** [comment]
No, the question was about suaveio-like api. But it's not so important. Thank you!

**Comment by dustinmoris** [comment]
Ok I understand. I didn't plan to expose a SuaveIO like socket implementation to be honest, but if you have some ideas I am open for it!

If we would do something with web sockets then in the spirit of Giraffe it would have to be on top of ASP.NET Core's web socket server.  The plan for Giraffe is to make the existing ASP.NET Core platform more functional rather than to replace it. Any suggestions to make the current ASP.NET Core web sockets more FSharpy are welcome :)

**Comment by forki** [comment]
I think the point of this is that having a F# sample will automatically show how it compares to the suave. Tbh I'm very interested in this scenario since keeping connections to thousands of clients is a the one interesting use case that I personally see for me
