### ISSUE TITLE
warbler not working

### ISSUE THREAD

**Issue by Potmos** [dustinmoris/Giraffe#83]
I followed the exact example  that there is on the site using warbler but I am getting page as a static result.
```
let time() =
    System.DateTime.Now.ToString()

let webApp =
    choose [
        GET >=>
            choose [
                route "/once"      >=> (time() |> text)
                route "/everytime" >=> warbler (fun _ -> (time() |> text))
            ]
    ]
```

**Comment by dustinmoris** [comment]
Sorry for this bug, I just pushed a fix for it. The change to the continuation format caused this issue and the test didn't test for it properly anymore, because we didn't pre-compile the webApp with the next continuation and therefore it didn't capture this bug. Both is fixed now and I'll release a new NuGet package in the next 10 minutes.

**Comment by Potmos** [comment]
Thanks a lot for the fix.
No need to be sorry it is still in beta and you've been doing a great job so far. Keep up the good work.

**Comment by algunion** [comment]
@dustinmoris, the warbler issue seems to be back (I encountered the issue on my custom code - but also added the simple example you provided - just to be sure I didn't mess up something else).

I am using Giraffe 6.0.0.

**Comment by algunion** [comment]
Sorry ... wrong call here. After reading some other issues, I discovered that there is already a global warbler defined.

After deleting my local warbler everything just works.
